// ─────────────────────────────────────────
// Quest.timely{} — SMARTER: T
// Marker configuration and container object (D05).
// Holds conditionType, the condition parameters, the Marker instances,
// and the computed projectedFinish date.
// This is NOT a flat Marker array — it is the full configuration object.
// ─────────────────────────────────────────

import type { RecurrenceRule } from '../taskTemplate';
import type { Marker, MarkerConditionType } from './Marker';

export interface QuestTimely {
  /**
   * Determines which field configures Marker generation for this Quest (D05).
   * All Markers in this Quest share the same conditionType.
   */
  conditionType: MarkerConditionType;
  /**
   * Shared recurrence rule — set if conditionType is interval, null otherwise.
   * Applied to all Markers in this Quest. Each Marker uses its own lastFired as anchor.
   */
  interval: RecurrenceRule | null;
  /**
   * Shared XP threshold — set if conditionType is xpThreshold, null otherwise.
   * Applied to all Markers in this Quest.
   */
  xpThreshold: number | null;
  /**
   * All projected and fired Marker instances for this Quest.
   * Initially empty — Markers are generated by the engine as conditions are met.
   */
  markers: Marker[];
  /**
   * Estimated completion date — computed from user schedule XP rate (D05).
   * BUILD-time task — null until computed by projection algorithm.
   * Input shape for algorithm TBD (see open question Q01 in MVP07 structure doc).
   */
  projectedFinish: string | null; // ISO date
}
